[package]
name = "imageuploader"
version = "0.1.0"
authors = ["zups <zupsor@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.12.0"
log = "0.4"
log4rs = "1.2"
